language: generic

dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - gfortran-4.9
            - libblas3
            - libblas-dev
      env: CC='gcc-4.9' FC='gfortran-4.9' LIBS='-L/usr/lib -lblas -lm'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
            - libblas3
            - libblas-dev
      env: CC='gcc-5' FC='gfortran-5' LIBS='-L/usr/lib -lblas -lm'
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - gfortran-6
            - libblas3
            - libblas-dev
      env: CC='gcc-6' FC='gfortran-6' LIBS='-L/usr/lib -lblas -lm'
    - os: osx
      env: GCC='gcc@4.9' CC='gcc-4.9' FC='gfortran-4.9'
    - os: osx
      env: GCC='gcc@5' CC='gcc-5' FC='gfortran-5'


env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    - LD_RUN_PATH=/usr/local/lib
    - PKG_CONFIG_LIBDIR=/usr/local/lib/pkgconfig

before_install:
  - |
    set -e
    if [ $TRAVIS_OS_NAME == osx ] ; then 
      brew uninstall --force $(brew list)
      brew cleanup -s
      brew update
      brew install ${GCC} autoconf automake libtool wget pkg-config
    fi

install:
  - |
    set -e
    wget http://ftp.heanet.ie/mirrors/gnu/gsl/gsl-2.3.tar.gz
    tar xfz gsl-2.3.tar.gz
    cd gsl-2.3
    ./configure
    make
    if [ $TRAVIS_OS_NAME == osx ]; then make install ; fi
    if [ $TRAVIS_OS_NAME == linux ]; then sudo make install ; fi
    cd ..

script:
  - |
    set -e
    autoreconf -fi
    ./configure CFLAGS="-Wall" FCFLAGS="-Wall"
    make
    make check
    make distcheck
    set +e

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

branches:
  only:
    - master
#os:
#  - osx
